### PR TITLE
Refresh rate adjustment and other fixes

### PR DESCRIPTION
**Pull request by guidosarducci**
Some upstream safety/correctness updates I came across and a fix for the broken refresh rate adjustment I ran into on AFTV v1.  These only have some runtime on my AFTV box.

Suggestions, changes, etc. welcome.

### CODE REVIEW

**Comment by guidosarducci** [comment]
@koying  Looks like you didn't see my mode API fix included here, but ended up solving it later independently.  I'll remove that commit and add a couple of others, including one that addresses #521 for me after tracking it down.  Please review.

**Comment by koying** [comment]
Missed this one, somehow ;)

**Comment by guidosarducci** [comment]
OK.  Any questions or comments?  Is there something else you need from me on these?  One item I did want your feedback on was commit ad3daec.

**Comment by koying** [comment]
Seems all fine.
Will merge and go from there.

Thanks

**Pull request merged**
