### PR TITLE
ADD: Define AndroidApps as a program section

### PR DESCRIPTION
**Pull request by elmerohueso**
Allows for ActivateWindow(Programs,AndroidApps) as shorthand for
ActivateWindow(Programs,androidapp://sources/apps/), to open
the Android Apps list directly.

### CODE REVIEW

**Comment by koying** [comment]
@elmerohueso Could you rebase, please

**Comment by elmerohueso** [comment]
I did "git rebase upstream/gotham", which forced me to manually update some files in conflict (I just copied yours manually into mine, but I don't know why they were in conflict in the first place), and now it shows 6 new commits.  That's can't be right :(  What am I doing wrong?  I seem to always run into issues rebasing.

**Comment by elmerohueso** [comment]
I figured out what went wrong.  Several files were still open in the editor, so their temp copies accidentally got committed.
I've rebased and squashed and all is well.

**Comment by koying** [comment]
Thanks. Actually you might want to propose this PR to xbmc self, nothing contentious in there. I'd then backport to spmc. 
Is it ok for you? Just ping me in the xbmc PR is so...

**Comment by koying** [comment]
Just one thing: please surround with "#ifdef TARGET_ANDROID"

**Comment by elmerohueso** [comment]
It was actually merged into the XBMC master a bit ago:
https://github.com/xbmc/xbmc/pull/5133,
https://github.com/xbmc/xbmc/commit/8dc71e7156e0fa0db1f1bf4d70357dd6569d2891
.
With the current functionality, the Programs dialog just defaults back to
the root of sources:// if you specify an unknown source, so checking for
ANDROID isn't really going to change the functionality (with or without the
check, if you call it on another platform, it'll still give a "not found"
error and fallback to sources://).  I'm thinking the responsibility to run
the platform check will be with skinners.

**Comment by koying** [comment]
Oh, ok.
If you see something interesting to be backported, just ping me the hash, no need to make a PR ;)

Re the ifdef, I agree it's not strictly necessary, but there is no point to drag code which never be executed in the binaries on non-android platforms.
But as it was accepted like this in master, I'll do the same ;)

**Comment by elmerohueso** [comment]
Cool.  I'd just done a separate pull request since SPMC uses the variable
"dir" and .Equals, while XBMC uses "lower" and ==.
For situations like that, where code would need to be modified to preserve
the functionality, do you want a separate pull request with the modified
code or to just ping you (via Issues?), anyway?

**Comment by koying** [comment]
Indeed, if code modifications are needed, better to do a PR, as you would already have done and tested the modifs.

**Comment by koying** [comment]
And yes, "issues" is fine for pinging

**Comment by koying** [comment]
Just created a "Backport" label for those

**Pull request merged**
