### PR TITLE
[xbmcZ] Adding to Frodo StartAndroidActivity to allow starting Android a...

### PR DESCRIPTION
**Pull request by JoKeRzBoX**
...pps

similarly to what already exists in the Gotham code base.

Sample call from a plugin (default.py file):
       xbmc.executebuiltin('XBMC.StartAndroidActivity("com.androidemu.gens")')

I compiled spmc with these changes and tested the APK and it does work. It is based on what was suggested in the forum by elmerohueso (http://ouyaforum.com/showthread.php?8220-SPMC-Koying&p=99046&viewfull=1#post99046), with some additional required changes to make it work.

### CODE REVIEW

**Comment by hessius** [comment]
Any way you could share the apk before this is merged?

**Comment by koying** [comment]
Could you please keep the "#if defined(TARGET_ANDROID)" as in https://github.com/xbmc/xbmc/commit/46d19ad6ded8559af9d398061666184d6947b177

**Comment by JoKeRzBoX** [comment]
I've uploaded the compiled app (spmc-armeabi-v7a.apk) to here so you guys can test: http://depositfiles.com/files/3cqmmwrgp
It is the latest SPMC released by koying with the addition of this feature only. 
I've also uploaded a sample "music" addon that uses the StartAndroidActivity. It tries to start Genesis emulator (com.androidemu.gens) but you can change the app name to any android app you want in the default.py file: http://depositfiles.com/files/bt92jmim7

koying - I agree with you to include the verification of target android. For my initial testing I just added the extra lines of code (since this version of XBMC is targeted for android anyways) but we should make the code clean and re-add the "#if defined(TARGET_ANDROID)". I will send another pull request for those (as I do not know how to modify the existing pull request).

Also just so you understand the changes I made, the Frodo base code already had a way to call Android apps using the StartActivity method but that was not exposed to the user. What I am doing here is just making that method available using code leveraged from Gotham version. Frodo and Gotham's versios of the underlying method CXBMCApp::StartActivity have different signatures (Frodo's receive just one parameter while Gotham's one accepts four) and I am keeping the Frodo version "as-is". The consequence for SPMC is that if StartAndroidActivity is called with more than one parameter, only the first parameter (package name) will be taken and that should be ok for majority of the cases (all the examples of use of StartActivity I've seen only have one parameter [package name] anyways).

Signature from Gotham:
 bool CXBMCApp::StartActivity(const string &package, const string &intent, const string &dataType, const string &dataURI)

Signature from Frodo:
 bool CXBMCApp::StartActivity(const string &package)

**Comment by hessius** [comment]
Thanks, a problem with your APK is that since it has the same package name but a different signature it can't be installed over SPMC retaining user settings.
For app launching plugins check out: https://github.com/hessius/XBMC-Spotify-Android-Launcher and https://github.com/EldonMcGuinness/XBMC-Netflix-Android-Launcher

**Comment by JoKeRzBoX** [comment]
Hi hessius - yes, that APK was just for my own test and uses different signature and personal cert. I do not by all means intend to release a newer version of SPMC. I will leave for koying to decide if he wants to incorporate these changes when he releases an SPMC 12.4.2 in the future.

Thanks for the links for all launching plugins. The ones I am using in my box are based on the Netflix one you mentioned. Having the StartAndroidActivity available allow us to also create direct links to android apps from skins as well (&lt;onclick&gt;XBMC.StartAndroidActivity("&lt;app name>")&lt;/onclick&gt;) and probably other creative uses that could make xbmc more suitable to be the default Launcher (which is my intention). 

For example, in my custom Confluence skin I have the following in the Settings.xml to have a direct link to Android Settings:
&lt;item id="9"&gt;
    &lt;label&gt;Android Settings&lt;/label&gt;
    &lt;label2&gt;Configure specific aspects of Android OS&lt;/label2&gt;
    &lt;onclick&gt;XBMC.StartAndroidActivity("com.android.settings")&lt;/onclick&gt;
    &lt;icon&gt;-&lt;/icon&gt;
&lt;/item&gt;

**Pull request closed without merging**
